---

plugins:
        # https://github.com/jest-community/eslint-plugin-jest
        - jest
        # https://github.com/babel/eslint-plugin-babel
        - babel
env:
        browser: true
        node: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
        -'airbnb-base'
        -'plugin:jest/recommended'

rules: 
        no-console: off 




                         
